import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Carolina Castelli
        </h1>

        <p className={styles.description}>
          A mais linda do mundo!
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Material A &rarr;</h2>
            <p>Descrição do Material A</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Material B &rarr;</h2>
            <p>Descrição do Material B</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/master/examples" className={styles.card}>
            <h2>Material C &rarr;</h2>
            <p>Descrição do Material C</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className={styles.card}>
            <h2>Material D &rarr;</h2>
            <p>Descrição do Material D</p>
          </a>
        </div>
      </main>
    </div>
  )
}
